language: groovy

sudo: false

jdk:
  - oraclejdk7

install: true

# NOTE: using git clone instead of gradle getGit for file order, causing problems on Travis with test class run order
before_script:
  - cd ..
  - git clone https://github.com/moqui/moqui-framework.git moqui
  - cd moqui
  - git clone https://github.com/moqui/moqui-runtime.git runtime
  - cd runtime/component
  - git clone https://github.com/moqui/mantle-udm.git
  - git clone https://github.com/moqui/mantle-usl.git
  - git clone https://github.com/moqui/SimpleScreens.git
  - git clone https://github.com/moqui/HiveMind.git
  - cd ../..
  - chmod +x gradlew

env:
  - TERM=dumb

script:
# using git commands instead:  - ./gradlew getGit -Pcomponent=HiveMind
  - ./gradlew load
  - ./gradlew runtime/component/HiveMind:test

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
